### ISSUE TITLE
Dense Feature example not working on Tensorflow 2.2.0-rc3

### ISSUE THREAD

**Issue by NiBurhe** [EgorBEremeev/SoloLearnML#1]
Hello Egor,

Many thanks for your Post on Stackoverflow and your example on Github.

I tried Dense Feature example, but it don't work on 2.2.0-rc3 anymore.

Details see attached pdf. Can you please check and assist me to get the example running?

Thanks & Regards,
Nils

[Answer. Tensorflow pad sequence feature column. DenseFeatures.pdf](https://github.com/EgorBEremeev/SoloLearnML/files/4512154/Answer.Tensorflow.pad.sequence.feature.column.DenseFeatures.pdf)

**Comment by EgorBEremeev** [comment]
@NiBurhe, Hi! Thanks for your note. I fixed df_to_dataset() function and now a dataset is produced correctly from the pandas dataframe. The rest concerning DenseFeatures stay the same.
